# Codecov configuration for Frai
# See: https://docs.codecov.io/docs/codecov-yaml

# Coverage targets and thresholds
coverage:
  precision: 2
  round: down
  range: "85...100"

  # Status checks
  status:
    # Overall project coverage
    project:
      default:
        target: 85%
        threshold: 2%
        informational: false
      # Critical areas requiring higher coverage
      api:
        target: 90%
        paths:
          - "api/"
        threshold: 1%
      services:
        target: 88%
        paths:
          - "services/"
        threshold: 2%
    
    # Pull request coverage
    patch:
      default:
        target: 80%
        threshold: 5%
        informational: false
      # New code should have good coverage
      new_code:
        target: 85%
        threshold: 3%

# Comment configuration
comment:
  layout: "reach,diff,flags,tree,footer"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes
  branches: null

# Ignore patterns
ignore:
  - "tests/"
  - "**/*test*.py"
  - "**/conftest.py"
  - "setup.py"
  - "main.py"  # Entry point, hard to test
  - "models/"  # Downloaded model files
  - "**/__pycache__/"
  - "venv/"
  - "env/"
  - "build/"
  - "dist/"
  - "*.egg-info/"
  # Ignore specific files that are hard to test
  - "services/ai/image_generation/models/"
  - "**/migrations/"

# GitHub integration
github_checks:
  annotations: true

# Notification settings
slack:
  default:
    only_pulls: false
    message: "Coverage for {{project}} changed ({{diff}}) via {{author}}"
    threshold: 1%
    branches: null
    flags: null
    paths: null

# Flags for different test types
flags:
  unit:
    paths:
      - tests/unit/
    carryforward: true
  integration:
    paths:
      - tests/integration/
    carryforward: true
  performance:
    paths:
      - tests/performance/
    carryforward: false  # Performance tests may be flaky
  blackbox:
    paths:
      - tests/blackbox/
    carryforward: true

# Component-based coverage tracking
component_management:
  individual_components:
    - component_id: api
      name: "API Layer"
      paths:
        - "api/"
    - component_id: services
      name: "Service Layer"  
      paths:
        - "services/"
    - component_id: ai_services
      name: "AI Services"
      paths:
        - "services/ai/"
    - component_id: chat_services
      name: "Chat Services"
      paths:
        - "services/chat/"

# Parsing configuration
parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

# Team and project settings (to be configured in Codecov dashboard)
team:
  coverage:
    target: 85%
    threshold: 2%
