# Grafana datasource configuration for Frai
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    orgId: 1
    basicAuth: false
    withCredentials: false
    jsonData:
      httpMethod: POST
      manageAlerts: true
      alertmanagerUid: alertmanager
      prometheusType: Prometheus
      prometheusVersion: "2.40.0"
      cacheLevel: 'High'
      disableRecordingRules: false
      incrementalQueryOverlapWindow: 10m
      queryTimeout: 60s
      timeInterval: "30s"
      tlsAuth: false
      tlsAuthWithCACert: false

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true
    orgId: 1
    basicAuth: false
    withCredentials: false
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: prometheus
          matcherRegex: "traceID=(\\w+)"
          name: TraceID
          url: "$${__value.raw}"

  - name: Personal Chatter DB
    type: postgres
    url: postgres:5432
    database: personal_chatter
    user: personal_chatter
    secureJsonData:
      password: personal_chatter_password
    jsonData:
      sslmode: disable
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      postgresVersion: 1300
      timescaledb: false
